# Setup
title:        Good Itea
tagline:      Created by Jihwan ma 2017-08-15
baseurl:
paginate:     1

# About/contact
author:
  name:       JiHwan Ma
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
